import { useState, useEffect, useCallback } from 'react';

export function Lightbox({
  selectedImage,
  setSelectedImage,
  generatedImages,
  generatedSlides,
  storyCaption,
  storyHashtags,
  topic,
  onDownloadImage
}) {
  const [copied, setCopied] = useState(false);

  const images = selectedImage?.board?.images || generatedImages || [];
  const totalImages = images.length;

  const handleClose = useCallback(() => {
    setSelectedImage(null);
  }, [setSelectedImage]);

  const handlePrev = useCallback((e) => {
    if (e) e.stopPropagation();
    if (selectedImage && selectedImage.idx > 0) {
      const newIdx = selectedImage.idx - 1;
      setSelectedImage({ src: images[newIdx], idx: newIdx, board: selectedImage.board });
    }
  }, [selectedImage, images, setSelectedImage]);

  const handleNext = useCallback((e) => {
    if (e) e.stopPropagation();
    if (selectedImage && selectedImage.idx < totalImages - 1) {
      const newIdx = selectedImage.idx + 1;
      setSelectedImage({ src: images[newIdx], idx: newIdx, board: selectedImage.board });
    }
  }, [selectedImage, totalImages, images, setSelectedImage]);

  // Keyboard navigation
  useEffect(() => {
    if (!selectedImage) return;

    const handleKeyDown = (e) => {
      switch (e.key) {
        case 'Escape':
          handleClose();
          break;
        case 'ArrowLeft':
          handlePrev();
          break;
        case 'ArrowRight':
          handleNext();
          break;
        default:
          break;
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [selectedImage, handleClose, handlePrev, handleNext]);

  if (!selectedImage) return null;

  const handleCopyCaption = () => {
    const caption = selectedImage.board?.caption || storyCaption;
    const hashtags = selectedImage.board?.hashtags || storyHashtags;
    const text = caption
      ? `${caption}\n\n${hashtags?.map(t => '#' + t).join(' ') || ''}`
      : '';
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const slideTitle = selectedImage.board?.slides?.[selectedImage.idx]?.title
    || generatedSlides[selectedImage.idx]?.title
    || topic;
  const caption = selectedImage.board?.caption || storyCaption;
  const hashtags = selectedImage.board?.hashtags || storyHashtags;

  return (
    <div className="lightbox-overlay" onClick={handleClose}>
      <button className="lightbox-close-btn" onClick={handleClose}>
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
          <path d="M18 6L6 18M6 6l12 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </button>

      {selectedImage.idx > 0 && (
        <button className="lightbox-nav lightbox-prev" onClick={handlePrev}>
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
            <path d="M15 18L9 12L15 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
      )}

      {selectedImage.idx < totalImages - 1 && (
        <button className="lightbox-nav lightbox-next" onClick={handleNext}>
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
            <path d="M9 18L15 12L9 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
      )}

      <div className="lightbox-content" onClick={e => e.stopPropagation()}>
        <div className="lightbox-image-container">
          <img src={selectedImage.src} className="lightbox-image" alt="" />
        </div>
        <div className="lightbox-details">
          <div className="lightbox-meta">
            <span>{selectedImage.idx + 1} of {totalImages}</span>
            <span>•</span>
            <span>Generated by AI</span>
          </div>
          <h2>{slideTitle}</h2>

          {caption && (
            <div className="caption-section">
              <label className="caption-label">The Narrative</label>
              <p className="caption-text">{caption}</p>
            </div>
          )}

          {hashtags?.length > 0 && (
            <div className="hashtags-section">
              <div className="hashtags-list">
                {hashtags.map((tag, i) => (
                  <span key={i} className="hashtag">#{tag}</span>
                ))}
              </div>
            </div>
          )}

          <div className="lightbox-actions">
            <button className={`overlay-btn copy-btn ${copied ? 'copied' : ''}`} onClick={handleCopyCaption}>
              {copied ? 'Copied!' : 'Copy Text'}
            </button>
            <button
              className="overlay-btn"
              onClick={() => onDownloadImage(selectedImage.src, selectedImage.idx)}
            >
              Download
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
